### ISSUE TITLE
Feature Request: Add Bug Filing Link to axe-sarif-converter

### ISSUE THREAD

**Issue by thisisnaty** [microsoft/axe-sarif-converter#1359]
We use the Accessibility Insights FastPass tool on the browser to create bugs. To automate this process, we're integrating Accessibility Insights FastPass with Playwright tests. It would be very helpful if the axe-sarif-converter could include a feature that generates a link for filing bugs, similar to the functionality provided by the Accessibility Insights browser extension. This would streamline our workflow and improve efficiency.

Thank you!

**Comment by joestegman425** [comment]
Thank you, Natalia, for the feedback. We have reviewed this request as well as the related item [#1576](https://github.com/orgs/microsoft/projects/869/views/1?pane=issue&itemId=73136246). Both items require a way to pass in GitHub or ADO repository context into the axe-sarif-converter such that the axe-sarif-converter can add additional context (the bug link) to the Sarif output (and it's not clear where this would go in the standardized sarif output). We appreciate the desire to improve workflows; however, the effort required to design and implement a solution for this issue, given the limited impact the solution will have on our broader customer base, is not something we are able to commit to at this point.

**Comment by joestegman425** [comment]
Not planned.
