### ISSUE TITLE
Package is not yet published

### ISSUE THREAD

**Issue by micahgodbolt** [Microsoft/axe-sarif-converter#21]
Are there plans to publish this as a package? https://www.npmjs.com/search?q=axe-sarif-converter

We'd like to be able to depend on this rather than using our own copy.

**Comment by Shobhit1** [comment]
Hi @micahgodbolt ,

Yes, there are plans to publish this package and we will update when we publish it. 

Thanks,
Shobhit

**Comment by Shobhit1** [comment]
Hey @micahgodbolt ,

Version 1.0.0 of the `axe-sarif-converter` is published. 
https://www.npmjs.com/package/axe-sarif-converter

**Comment by Shobhit1** [comment]
Closing the issue as the package is being published. 👍 
Thank you @micahgodbolt for creating this issue.

**Comment by micahgodbolt** [comment]
aaaaaaaaaaaaaaaaaaaawesome!
