### ISSUE TITLE
This package requires yarn >1.15.1, seems really aggressive

### ISSUE THREAD

**Issue by kenotron** [microsoft/axe-sarif-converter#70]
I'm not sure what features are required from recent releases of yarn, but this makes it so that all your consumers will have to have a yarn version above 1.15. This likely isn't the most friction free way to consume this library. Perhaps you don't need this requirement?

**Comment by dbjorge** [comment]
Thanks very much for letting us know! We didn't realize that engine requirement was transitive; I'd mistakenly assumed it just applied to folks directly developing this project. We'll loosen the requirement :)
