### ISSUE TITLE
Generated SARIF is incompatible with codeql schema

### ISSUE THREAD

**Issue by pamelafox** [microsoft/axe-sarif-converter#961]
The generated sarif file produces output like:

```
locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "src/flaskapp/__init__.py",
                  "index": 0
                },
                "region": {
                  "snippet": {
                    "text": "<html>"
                  }
                }
              },
              "logicalLocations": [
                {
                  "fullyQualifiedName": "html",
                  "kind": "element"
                }
              ]
            }
          ]
        },
```

However, the Github CodeQL SARIF upload requires additional fields in the region to determine a line number. See schema:
https://github.com/oasis-tcs/sarif-spec/blob/main/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json#L1709

Here is my sophisticated post-processing step for adding a line number:

sed -i 's/"snippet"/"startLine":1,"startColumn":1,"endColumn":1,"snippet"/g' src/tests/axe_results.sarif

That works, and results in scan results that look like this:

![Screenshot 2023-04-04 at 11 42 09 AM](https://user-images.githubusercontent.com/297042/229891495-783f49c1-2282-46a6-a4da-f3c434b0542e.png)

Obviously that is not very accurate, but it at least makes CodeQL happy.
Perhaps I should also open a pull request on https://github.com/github/codeql-action/issues?q=is%3Aissue+is%3Aopen+location for making those location fields optional. I'm not sure what the right approach is here, just opening this issue for discussion and posterity.

**Comment by DaveTryon** [comment]
@pamelafox, thanks for opening this. Given the choice between an optional field and a mandatory field with meaningless data, the optional field seems like a better option. Of course, that assumes that all downstream components can properly handle the optional field, which may take some time to achieve. Adding the meaningless data isn't necessarily difficult, but it feels like it's fixing the wrong problem.

**Comment by dbjorge** [comment]
I agree with Dave - these results don't have any way to meaningfully include a line number (they often correspond to dynamically injected DOM content that doesn't correspond to any particular line of an HTML file), so my preference would be to avoid populating with meaningless data.

I could maybe imagine us moving the snippet out of `location.physicalLocation.region.snippet` and into `location.message` to adhere better to the letter of the spec, but that would be a breaking change for the ADO extension. I think it would make more sense to ask CodeQL to handle the case where a result has a snippet but no line information.

**Comment by dbjorge** [comment]
We discussed this internally and we think that populating with the placeholder info by default like Pamela's original suggestion is probably the least-bad engineering tradeoff between "not breaking backcompat with the ADO viewer" and "not forcing every user in Pamela's position to make their own workaround".

**Comment by pamelafox** [comment]
I believe GitHub CodeQL has a higher threshold for required properties, per:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#physicallocation-object

I'm not sure if I tried removing startColumn/endColumn. I've pinged a GitHub engineer on CodeQL team to see if they can confirm what's required. (I ended up removing this from my workflow, so I could try it out myself, but it would take a bit of time).

**Comment by aegilops** [comment]
Pamela is totally right - GitHub Code Scanning goes beyond the SARIF spec in what is required.

I'm not quite a CodeQL engineer - I'm in Field Services - but I asked some of our CodeQL Engineers about this to make sure I had things straight for you.

Looking at the [SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317673), it's invalid to provide a region without _any_ location information, regardless Code Scanning's additional validation/requirements.

When you are uploading to Code Scanning with the REST API you can [set a flag to ask for the SARIF to be validated according to its requirements](https://docs.github.com/en/rest/code-scanning?apiVersion=2022-11-28#upload-an-analysis-as-sarif-data--parameters).

The [SARIF Validator](https://sarifweb.azurewebsites.net/Validation) website does also have a "GitHub ingestion rules" checkbox that should apply the same validation.

Code Scanning is very much set up to display results of problems that are localisable to the code itself, vs. problems that appear in artefacts produced by the code; we have a similar issue with how to display results of black box dynamic analysis that don't map obviously to source locations.

**Comment by DaveTryon** [comment]
@pamelafox, this shipped in https://github.com/microsoft/axe-sarif-converter/releases/tag/v2.10.1. We're closing this on our end

**Comment by pamelafox** [comment]
Thank you, @DaveTryon! I'll likely be mentioning axe-sarif-converter in an upcoming talk (as well as showing other ways to surface axe results, since code quality isn't always the right location).
